### ISSUE TITLE
Getting rsparkling to send jobs to the spark cluster

### ISSUE THREAD

**Issue by renegademonkey** [h2oai/rsparkling#15]
Hi there,

I've just finally managed to set up my stack to use RStudio to connect to a local spark cluster (with file storage in CassandraDB) via sparklyR. I can also get h2o working locally without a problem.

I am now trying to use rsparkling to run h2o algorithms on the spark cluster. I've read all the documentation and am still not sure I understand how sparking water is workign in this context.

While I can access spark dataframes (pulled in from cassandra) and convert them to h2o frames and access them and munge them, in RStudio when I run an h2o model it appears to be executing it locally rather than on the spark cluster (it doesn't show up as a spark job). Does h2o need to be installed on the cluster as well? I thought it was set up on the cluster automatically when I started my spark context with rsparkling loaded in RStudio? 

My setup is as follows:
Spark version (on cluster & locally): 2.0.0
h2o library in RStudio: 3.10.0.7
rsparkling: 0.1.0

My process is as follows:

Load libraries
```
library(dplyr)
library(sparklyr)
```
sucessfully create a spark context 
`sc <- spark_connect(master = "spark://<spark_cluster_address>:7077", config = spark_config(config.yml), version = 2.0.0)
`
 
Check that sparklingwater registered h2o to be made available to the sparkContext
```
h2o_context(sc)

<jobj[58]>
  class org.apache.spark.h2o.H2OContext
  
Sparkling Water Context:
 * H2O name: sparkling-water-user_1604847048
 * cluster size: 2
 * list of used nodes:
  (executorId, host, port)
  ------------------------
  (1,<host_ip_0>,54321)
  (0,<host_ip_1>.182,54321)
  ------------------------

  Open H2O Flow in browser: http://<host_ip_2>:54321 (CMD + click in Mac OSX)
```

Load h2o library & connect R and h2o to the spark cluster (using above address?)
```
library(h2o)
h = h2o.init(ip="host_ip_2", port=54321)

 Connection successful!

R is connected to the H2O cluster (in client mode): 
    H2O cluster uptime:         37 minutes 22 seconds 
    H2O cluster version:        3.10.0.7 
    H2O cluster version age:    4 months and 13 days !!! 
    H2O cluster name:           sparkling-water-<user>_1604847048 
    H2O cluster total nodes:    2 
    H2O cluster total memory:   18.98 GB 
    H2O cluster total cores:    64 
    H2O cluster allowed cores:  64 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          <host_ip_2> 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    R Version:                  R version 3.3.2 (2016-10-31) 
```

From here on I can upload local R df's into spark, convert the resulting spark df's into h2o dataframes. These show up as jobs in spark, but any data munging or h2o algorithms I run on these h2o dataframes seem to be executed locally rather than on the spark cluster. Did I miss something?

Any help appreciated.

**Comment by navdeep-G** [comment]
@renegademonkey The H2O jobs you are submitting should show up in the H2O logs. You can point your browser to ` http://<host_ip_2>:54321` and navigate to the logs. Also, you can look at the water meter in Flow to see CPU usage as a H2O algorithm/job is running.

**Comment by ledell** [comment]
@renegademonkey @navdeep-G Don't forget about the `rsparkling::h2o_flow()` function which will automatically open a window in your browser (so you don't have to manually type the IP & port in the address bar).

**Comment by renegademonkey** [comment]
@navdeep-G and @ledell Thanks for the fast response! 

So I can always see the flow interface (that's fine), and can look at the info log in flow and at the water meter. When an ML algorithm is being run, the water meter spikes and I can see the results in the flow interface (as well as the Rstudio interface). 

What I don't understand is why I can't see the h2o ML processes come up as Spark jobs on my main Spark interface  - i.e. although the `as_h2o_frame()` processes are visible as Spark jobs, the `h2o.glm()` processes are not. Also, the cluster has 6 nodes, and rsparkling via the Spark context only sees/connects to 2 nodes, and thus `h2o.init()` only connects to 2 nodes. 

Even stranger, in my spark context config file I have granted each node access to 5 cores / 32gb ram (which is what the Spark interface is showing is accessible on each note to my sparklyr job), but the `h2o.init()` output shows that `H2O cluster allowed cores:  64` (which is the TOTAL number of cores on these two nodes. And even stranger, the flow water meter is showing 181 cores on each node?

Any ideas what is happening here? Are my h2o algos actually been computed on the Spark cluster, or locally (as it appears)?

**Comment by navdeep-G** [comment]
@renegademonkey The h2o ML processes do not show up in the Spark logs because they are an H2O process. Currently, Sparkling Water does not have the capability of outputting h2o logs to Spark logs. 

The reason `as_h2o_frame()` shows up in the Spark logs is because it is transferring a Spark frame to an h2o frame, which makes it technically a Spark job.

Also, I think you're issue with the cores is due to you explicitly connecting to h2o on the same cluster. `rsparkling` will connect you to the cluster that is available via sparklyr and you can continue to do h2o operations on that cluster. Can you share your code and config file?

**Comment by renegademonkey** [comment]
@navdeep-G - that's interesting that h2o doesn't show up in the spark logs, I would have thought that since it was integrated into the sparklyr spark app it's activity would show up that way. Does this have implications for resource management? I.e. does it mean that h2o can run on the spark cluster and hog all the resources?

So there are two issues which I have are:

1) When I start the spark context via sparlyr and with rsparkling loaded, I am only connected to 2 nodes out of 6 (as shown by running `h2o_context(sc)` ).

2) h2o seems to be utilising ALL the cores on those nodes (as shown by `H2O cluster allowed cores:  64` ), rather than respecting limitations set in the config file on the number of cores allowed by the sparklyr connection. Is there another set of configs I should be setting for h2o specifically?

My config.yml file settings are as follows:

```
default:
# local settings
  sparklyr.sanitize.column.names: TRUE
  sparklyr.cores.local: 3
  sparklyr.shell.driver-memory: "8G"

# remote core/memory settings
  spark.executor.memory: "8G"
  spark.executor.instances: 6
  spark.num.executors: 6
  spark.executor.cores: 5
  spark.cores.max: 12
  spark.memory.fraction: 0.75
  spark.memory.storageFraction: 0.5
  
# other configs for spark
  spark.serializer: org.apache.spark.serializer.KryoSerializer
  spark.executor.extraClassPath: /var/lib/cassandra/jar/guava-18.0.jar
 
# cassandra settings
  spark.cassandra.connection.host: <cassandra_db_ip>
  spark.cassandra.auth.username: <username>
  spark.cassandra.auth.password: <password>


# spark packages to load
  sparklyr.defaultPackages: 
    - com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M1
    - com.databricks:spark-csv_2.11:1.3.0
    - com.datastax.cassandra:cassandra-driver-core:3.0.2
    - com.amazonaws:aws-java-sdk-pom:1.10.34
```
